### ISSUE TITLE
controller no longer works since runtime-version 23.08

### ISSUE THREAD

**Issue by emememu** [flathub/info.cemu.Cemu#100]
Commit 10cda4d1abe65a1229d592aaf8ac80a50d779b8e caused my controller to stop working in Cemu. It still shows up as "PS4 Controller [SDLController]" in the list, but inputs are ignored, both in the Input Settings and in games.

Editing Cemu's manifest to use runtime-version: 22.08 (and rebuilding the flatpak) restores controller functionality.

Ryujinx and Yuzu flatpaks still handle my controller just fine after both of them moved to runtime 23.08.

**Comment by ColinKinloch** [comment]
Is the controller connected via Bluetooth or USB?

**Comment by ColinKinloch** [comment]
Does re-adding the controller with the minus and plus buttons?
![Screenshot from 2023-12-17 17-28-00](https://github.com/flathub/info.cemu.Cemu/assets/334272/2c97c6ba-d13c-4f2f-97dd-bf75fa932e1c)

**Comment by emememu** [comment]
It's a bluetooth controller.

> Does re-adding the controller with the minus and plus buttons?

Yes! That did the trick.

Is this something that should be documented, perhaps?

In any case, thank you!

**Comment by ColinKinloch** [comment]
Good to hear!
I don't think it's needs to be documented.
Hopefully it won't happened every time there is a new free desktop platform version
