### ISSUE TITLE
Change `<check_update>true</check_update>` to false

### ISSUE THREAD

**Issue by davidhedlund** [flathub/info.cemu.Cemu#162]
Flapak packages are not updated from the GUI, but from flatpak itself.

### Current Behavior

The appimage generates
`<check_update>true</check_update>`

### Expected Behavior

`<check_update>false</check_update>`

### Steps to Reproduce

open cemu. read ~/.config/Cemu/settings.xml

### System Info (Optional)

OS: GNU/Linux

**Comment by ColinKinloch** [comment]
You should open this on the upstream repo.
It also covers behaviour for distro packages also.

This line https://github.com/cemu-project/Cemu/blob/2e829479d9f63dcfbd8ef67d456793a70f684b18/src/config/CemuConfig.h#L416 should have a macro setting the value to `true` `#if LINUX && !APPIMAGE`

**Comment by davidhedlund** [comment]
> You should open this on the upstream repo. It also covers behaviour for distro packages also.

Thanks:
* https://github.com/cemu-project/Cemu/issues/1413
