### ISSUE TITLE
Dark theme not applying

### ISSUE THREAD

**Issue by deadmeu** [flathub/info.cemu.Cemu#17]
Running the latest Flatpak (compiled Apr 15) on Arch Linux KDE Plasma (Wayland) I get the light theme rather than my currently active dark theme.

This was not an issue while I was using the [cemu-bin package from the AUR](https://aur.archlinux.org/packages/cemu-bin) (dark theme was picked up correctly by default). As soon as I migrated over to the Flatpak I noticed the light theme being used instead.

**Comment by ColinKinloch** [comment]
I've had this issue intermittently with a few flatpak apps. Not sure what causes it.
Related: https://github.com/flathub/org.gtk.Gtk3theme.Breeze/issues/97

**Comment by ColinKinloch** [comment]
I think this is probably beyond the scope of this repo. Maybe the solution can be found in Cemu, gtk, flatpak or wxWidgets my money's on wxWidgets.

See #56 for a work around... maybe

**Comment by ColinKinloch** [comment]
The Cemu has some wxGTK specific code.
