### ISSUE TITLE
[Wayland] Image looks darker than it should while in game

### ISSUE THREAD

**Issue by TheFortunattor** [flathub/info.cemu.Cemu#26]
## Description
On Fedora Silverblue 38 using Nvidia (RTX 3070), when I open a game on Cemu using the Vulkan backend, the image looks significantly darker than it should. This only happens on the flatpak version, using Wayland and the Vulkan backend while selecting "Nvidia GeForce RTX 3070" as the Graphics device. The error fixes itself when using OpenGL or using X11 (with Vulkan). It also doesn't happen if I select llvmpipe as the graphics device. 

Looking at the logs from the Flatpak and Appimage versions, the only thing I can see for what might be wrong is that on the Flatpak version, there is an extra line that says "Vulkan: Can't find immediate present mode". 

I've uploaded both logs from each version. 

Here is a screenshot of the issue. Left is Flatpak and right is Appimage.

![Screenshot_20230420_162715](https://user-images.githubusercontent.com/50719030/233474088-e411c779-97bd-42ca-9689-460b552d1a70.png)

[log(flatpak).txt](https://github.com/flathub/info.cemu.Cemu/files/11290061/log.flatpak.txt)
[log(appimage).txt](https://github.com/flathub/info.cemu.Cemu/files/11290062/log.appimage.txt)

If you need more information or something else, I'd be happy to help! Thank you for reading this, and thank you for maintaining the flatpak version.

**Comment by ColinKinloch** [comment]
"Vulkan: Can't find immediate present mod" seems to happens when the vsync setting is unsupported by the vulkan implementation.
Does setting vsync to any of the other states in Cemu help?
Alternatively using mesa-git might proove fruitful:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/Mesa-git

**Comment by TheFortunattor** [comment]
Thank you for your quick reply. Setting vsync to Double or triple buffering doesn't affect things. 

I followed the instructions to install mesa-git and run Cemu like this "FLATPAK_GL_DRIVERS=mesa-git flatpak run info.cemu.Cemu"

However, doing so it makes Cemu unable to detect the specific graphics card and instead only showing the option for llvmpipe (which as I've said, strangely works). However, I still wanted to file this bug report because on the Appimage version, selecting the Nvidia card in graphics device works as intended.

**Comment by TheFortunattor** [comment]
Looking at the logs for using mesa-git and lvmpipe, it still shows "Vulkan: Can't find immediate present mod" but it's working so that must not be it. 

Here is the log for that

[log(mesa-git llvmpipe).txt](https://github.com/flathub/info.cemu.Cemu/files/11290778/log.mesa-git.llvmpipe.txt)

**Comment by ColinKinloch** [comment]
llvmpipe is a software renderer so it's unsurprising that it would work differently.
I have no experience with proprietary Nvidia graphics with flatpak, does the flatpak version match your installed system version?
Beyond that if running it running Cemu under Xwayland with `--nosocket=wayland` fixes the issue you should do that.

**Comment by TheFortunattor** [comment]
Yes, the flatpak matches the system version, both at "530.41.03". Removing the wayland socket with flatseal does fix the issue. After you said that, I looked into it some more and it looks like the appimage version is running under x11 via xwayland. 

Is there a way to force the appimage to use wayland? I tried setting "export GDK_BACKEND=wayland" on my .bash_profile but it doesn't seem to work. I want to see if running the appimage under wayland causes the same issue as in the flatpak.

**Comment by ColinKinloch** [comment]
I'm not sure why it would be using X11.
You could confirm the value in your shell before executing the AppImage with `echo $GDK_BACKEND`.

**Comment by TheFortunattor** [comment]
I'm not sure either. I can confirm that doing "echo $GDK_BACKEND" gives me back wayland but it still runs on X11 (I can confirm by doing the xeyes trick that follows x11 windows). Should I report this issue on the main repo?

Sorry for the delay

**Comment by ColinKinloch** [comment]
Maybe this? https://github.com/cemu-project/cemu_graphic_packs/issues/504

**Comment by TheFortunattor** [comment]
I'm not using any graphics mods though, and even so, everything even the UI is still dark. Out of curiosity I tried one but it made things even darker lol

**Comment by ColinKinloch** [comment]
Since it doesn't seem related to that mod it should be a new issue report.
Also keep this one open until you've verified that it's also present in the AppImage.

**Comment by TheFortunattor** [comment]
Will do, thanks. I tried to figure out how to enable wayland and saw a change that was made before about not assuming GDK_BACKEND=x11 so that's why I tried that but it's not working for whatever reason. 

I'll open a new issue and ask about using wayland on the appimage. If anything happens, I'll give you an update

**Comment by TheFortunattor** [comment]
Ok, I've done that and I got some odd results. There was a warning on commenting out the X11 backend and for a good reason it seems. While it opens, the fonts are all screwed up and upon trying to open a game with Vulkan, I am met with the message of "Error initializing Vulkan renderer. Error attempting to create a swapchain" and then hangs. 

But, loading a game with OpenGL seemingly works fine along with everything else, it picked my dualsense controller, audio works and all that. 

This is when trying to open it with vulkan:

![Screenshot_20230427_002539](https://user-images.githubusercontent.com/50719030/234754425-1de205a7-7de9-4173-aa3c-34e71c1715eb.png)

And here with OpenGL:

![Screenshot_20230427_004147](https://user-images.githubusercontent.com/50719030/234754508-164d62fc-0568-47cf-b522-c791596dd175.png)
![Screenshot_20230427_003351](https://user-images.githubusercontent.com/50719030/234754513-18cf822a-3a7c-4008-86d2-83d267a78bee.png)

[log(appimage wayland opengl).txt](https://github.com/flathub/info.cemu.Cemu/files/11339381/log.appimage.wayland.opengl.txt)

I can't get the logs for Vulkan but here are the ones from when choosing OpenGL. Not sure then what the flatpak does differently that makes it work, albeit with the issue mentioned above

**Comment by TheFortunattor** [comment]
This was resolved here https://github.com/cemu-project/Cemu/issues/792, https://github.com/cemu-project/Cemu/issues/792#issuecomment-1526551084. 

I looks like as of today, with Nvidia drivers 530.41.03, the drivers lack support for `FORMAT_B8G8R8A8_SRGB` on `VK_KHR_wayland_surface surfaces`.
