### ISSUE TITLE
Controller abnormal, can only identify the left stick, other keys can not be identified

### ISSUE THREAD

**Issue by jcleng** [flathub/info.cemu.Cemu#31]
flatpak --version
Flatpak 1.14.0

Gamesir-T4pro_E123
Device: /dev/input/js0

jstest-gtk normal identification, and windows10/11 version also works fine

**Comment by ColinKinloch** [comment]
Does this issue also exist on the AppImage version?

**Comment by jcleng** [comment]
> Does this issue also exist on the AppImage version?

not test for appimage, I changed the controller mode to Nintendo Switch controller mode can be used, before use the xbox mode

**Comment by ColinKinloch** [comment]
Unless you've identified that this issue only exists on the flatpak build of Cemu you should report this on the main Cemu repo or ask for help on their discord.

Feel free to reopen once you've checked that the issue is absent from the AppImage build.
