### ISSUE TITLE
No UI languages in Flatpak.

### ISSUE THREAD

**Issue by Amnesia1000** [flathub/info.cemu.Cemu#38]
When opening the Flatpak version of Cemu, in General Settings > General, when trying to change the emulator language, only the Default and English options appear.

**Comment by ColinKinloch** [comment]
Is it working for you?
I was failing to verify it was working until I ran:
```bash
flatpak config --set extra-languages fr
```

**Comment by Amnesia1000** [comment]
Its work un the last update
