### ISSUE TITLE
Discord Rich Presence 

### ISSUE THREAD

**Issue by pollux56** [flathub/info.cemu.Cemu#4]
Currently discord rich presence isn't working with the Flatpak version of cemu as it's sandboxed. You may be able to fix this by changing some permissions 
https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by ColinKinloch** [comment]
I've read that, this flatpak has `--filesystem=xdg-run/app/com.discordapp.Discord:ro` set.
And linking to `discord-ipc-*` is set in the wrapper script.
If you can create a pull request that gets it working I'd be extremely grateful.

**Comment by pollux56** [comment]
sorry lol guess ill reopen it. discord rich presence only works on flatpak discord when using cemu flatpak, but on the rpm (fedora) discord version it doesnt show up. the appimage of cemu does come up for the rpm discord, is this normal?

**Comment by pollux56** [comment]
woops reopen again. discord rich presence only works on flatpak discord when using cemu flatpak, but on the rpm (fedora) discord version it doesnt show up. the appimage of cemu does come up for the rpm discord, is this normal?

**Comment by ColinKinloch** [comment]
If you're looking for a solution to this the issues section of the discord flatpak is more likely to yield results.
Maybe once you get an answer add a section to the [discord flatpak wiki](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)) under a new title "Sandboxed applications with system discord" or something.
