### ISSUE TITLE
Unable to convert to wua file

### ISSUE THREAD

**Issue by emarleau** [flathub/info.cemu.Cemu#6]
Hello, when I try to convert my Wii U dumps to wua a window popup with this message : Error Unable to create file.

On the native build, it's working as expected.

**Comment by ColinKinloch** [comment]
Could you test switching the filesystem option from `host:ro` to `host`?
Can be done by running it as `flathub run --filesystem=host info.cemu.Cemu` or you could use flatseal.

**Comment by emarleau** [comment]
Changing the filesystem option to `host` fixed the problem. Thank you!
